### ISSUE TITLE
something wrong with the dimension

### ISSUE THREAD

**Issue by zzz123xyz** [jcreinhold/niftidataset#6]
something wrong with the dimension in the following cell.
I have to use squeeze to get the [32,32] image. 

https://github.com/jcreinhold/niftidataset/blob/master/tutorials/5min-tutorial.ipynb
cell [9]
src,tgt = ds[0]

Also when I run cell [18], the dimension is not correct, the input requires 4 dimensions [64, ....]
but the input has 5 dimensions [1, ,3, 1, 32, 7]. Dont know what was wrong there. could you fix it.
Thanks very much

**Comment by jcreinhold** [comment]
The tutorial has been updated. Let me know if you run into further issues and I'll reopen.
